table _Time_Intelligence_Measures
	lineageTag: fd3478d4-de6c-4fc4-b48e-25c76a30c6ff

	measure 'YTD Generation (MWh)' = ```
			TOTALYTD(
			                            [Total Generation (MWh)], 
			                            DimDate[Date]
			                        )
			```
		displayFolder: YEAR-TO-DATE (YTD)
		lineageTag: 4b5c9cd5-a482-41db-83a7-824ee6751aa5

		formatStringDefinition = "#,##0 MWh"

	measure 'YTD Fuel Cost ($M)' =
			TOTALYTD(
			                        [Total Fuel Cost ($M)],
			                        DimDate[Date]
			                    )
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		displayFolder: YEAR-TO-DATE (YTD)
		lineageTag: 2f89e419-3df3-4344-bbcd-e3ed7ba695eb

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'YTD CO2 Emission (MT)' =
			TOTALYTD(
			                            [Total CO2 Emissions (MT)],
			                            DimDate[Date]
			                        )
		displayFolder: YEAR-TO-DATE (YTD)
		lineageTag: 26cbc086-e2a7-473c-b94d-472b54e43aa2

		formatStringDefinition = "#,##0 MT"

	measure 'QTD Generation (MWh)' = ```
			TOTALQTD(
			                            [Total Generation (MWh)],
			                            DimDate[Date]
			                        )   
			```
		lineageTag: ba62cf0c-ae1c-46c7-b7ad-27acab64a965

		formatStringDefinition = "#,##0 MWh"

	measure 'MTD Generation (MWh)' =
			TOTALMTD(
			                            [Total Generation (MWh)],
			                            DimDate[Date]
			                        )
		lineageTag: 96c36d19-9147-42d9-82de-88a8c7e04e63

		formatStringDefinition = "#,##0 MWh"

	measure 'PY Generation (MWh)' =
			CALCULATE(
			                            [Total Generation (MWh)],
			                            SAMEPERIODLASTYEAR(DimDate[Date])
			                        )
		lineageTag: 8871a3eb-1c69-4f79-a456-89436972f913

		formatStringDefinition = "#,##0 MWh"

	measure 'YoY Growth (MWh)' = [Total Generation (MWh)] - [PY Generation (MWh)]
		lineageTag: bf534c1c-bd3f-4dd5-bb8a-c942b20e3291

		formatStringDefinition = "#,##0 MWh"

	measure 'YoY Growth %' =
			DIVIDE(
			                    [YoY Growth (MWh)],
			                    [PY Generation (MWh)],
			                    BLANK()
			                )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a21f9971-772b-4627-b87e-f3f907b7b711

	measure 'PY Capacity (MW)' =
			CALCULATE(
			                        [Total Capacity (MW)],
			                        SAMEPERIODLASTYEAR(DimDate[Date])
			                    )
		lineageTag: 0a2d0846-35b4-4fff-9d60-bcd3df74be1c

		formatStringDefinition = " #,##0.0 MW"

	measure 'YoY Capacity Change (MW)' = [Total Capacity (MW)] - [PY Capacity (MW)]
		lineageTag: 39222a85-0ca0-47d7-9d49-7ebc72619fe3

		formatStringDefinition = "+#,##0.0;-#,##0.0;0.0 MW"

	column Column
		isHidden
		formatString: 0
		lineageTag: 56c75425-a98f-4c94-b186-12eb7dd760e4
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Time_Intelligence_Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = a93ab34adac74b9a99f13c2efda0c732

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

