table DimGenerator
	lineageTag: c0fca99a-1d5e-4d7a-9a34-0ac2107549bc

	column GeneratorKey
		dataType: string
		lineageTag: 40f837c1-74d7-4826-953b-5c520a763ab3
		summarizeBy: none
		sourceColumn: GeneratorKey

		annotation SummarizationSetBy = Automatic

	column plant_id_eia
		dataType: string
		lineageTag: bb460632-02bf-49ed-80be-130c3a8225f0
		summarizeBy: none
		sourceColumn: plant_id_eia

		annotation SummarizationSetBy = Automatic

	column generator_id
		dataType: string
		lineageTag: b9819926-b7b1-4286-8e04-543246eb6c1b
		summarizeBy: none
		sourceColumn: generator_id

		annotation SummarizationSetBy = Automatic

	column fuel_type_code_pudl
		dataType: string
		lineageTag: 6e3c4e6d-3b83-4aa1-8d1b-b5a29d09878a
		summarizeBy: none
		sourceColumn: fuel_type_code_pudl

		annotation SummarizationSetBy = Automatic

	column technology_description
		dataType: string
		lineageTag: 64c9ac62-c8a8-4e32-8d6e-fd737cbd49e9
		summarizeBy: none
		sourceColumn: technology_description

		annotation SummarizationSetBy = Automatic

	column prime_mover_code
		dataType: string
		lineageTag: 85d39596-a5c7-4fe6-85f0-eabb0f86e4ab
		summarizeBy: none
		sourceColumn: prime_mover_code

		annotation SummarizationSetBy = Automatic

	column technology_category
		dataType: string
		lineageTag: 674c1c93-d12c-4892-9a8a-2bb07d10d5d5
		summarizeBy: none
		sourceColumn: technology_category

		annotation SummarizationSetBy = Automatic

	column is_renewable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 96a8b734-fc1f-4c2d-b3f1-8d085598fc77
		summarizeBy: none
		sourceColumn: is_renewable

		annotation SummarizationSetBy = Automatic

	column generator_operating_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c00a209e-bbe1-4134-ae53-2a29867040df
		summarizeBy: none
		sourceColumn: generator_operating_date

		variation Variation
			isDefault
			relationship: 75012203-4a4f-4814-a01f-53fdc50f9db4
			defaultHierarchy: LocalDateTable_3fa2870f-c43f-4cc0-909d-6d21e0b8e4b0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column generator_retirement_date
		dataType: string
		lineageTag: 26c3fe86-7d87-4a0a-8c3c-4e4cb3ef492e
		summarizeBy: none
		sourceColumn: generator_retirement_date

		annotation SummarizationSetBy = Automatic

	column planned_generator_retirement_date
		dataType: string
		lineageTag: cef4f5ce-d8ad-4ae1-9d80-107a45735db9
		summarizeBy: none
		sourceColumn: planned_generator_retirement_date

		annotation SummarizationSetBy = Automatic

	partition DimGenerator = m
		mode: import
		source =
				let
				    Source = out_eia__monthly_generators,
				
				SelectColumns = Table.SelectColumns(Source, {
				        "plant_id_eia",
				        "generator_id",
				        "fuel_type_code_pudl",
				        "technology_description",
				        "prime_mover_code",
				        "generator_operating_date",
				        "generator_retirement_date",
				        "planned_generator_retirement_date"
				    }),
				
				    RemoveNulls = Table.SelectRows(
				        SelectColumns,
				        each [plant_id_eia] <> null and [generator_id] <> null
				          and Text.Trim(Text.From([plant_id_eia])) <> ""
				          and Text.Trim(Text.From([generator_id])) <> ""
				    ),
				
				    // Clean key parts (stable across refresh/machines)
				    CleanParts = Table.TransformColumns(
				        RemoveNulls,
				        {
				            {"plant_id_eia", each Text.Upper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				            {"generator_id", each Text.Upper(Text.Trim(Text.Clean(Text.From(_)))), type text}
				        }
				    ),
				
				    // If GeneratorKey already exists, remove it (prevents your error)
				    RemoveExistingKey =
				        if List.Contains(Table.ColumnNames(CleanParts), "GeneratorKey")
				        then Table.RemoveColumns(CleanParts, {"GeneratorKey"})
				        else CleanParts,
				
				    AddIndex = Table.AddIndexColumn(RemoveExistingKey, "RowIndex", 1, 1, Int64.Type),
				
				    AddGeneratorKey = Table.AddColumn(
				        AddIndex,
				        "GeneratorKey",
				        each [plant_id_eia] & "-" & [generator_id],
				        type text
				    ),
				
				    // Deterministic de-dup: sort inside each group and keep 1 row
				    Grouped = Table.Group(
				        AddGeneratorKey,
				        {"GeneratorKey"},
				        {{"r", each Record.RemoveFields(
				                Table.First(Table.Sort(_, {{"RowIndex", Order.Ascending}})),
				                {"GeneratorKey"}
				            ), type record}}
				    ),
				
				    Expanded = Table.ExpandRecordColumn(
				        Grouped,
				        "r",
				        List.RemoveItems(Table.ColumnNames(AddGeneratorKey), {"GeneratorKey"})
				    ),
				
				    RemoveIndex = Table.RemoveColumns(Expanded, {"RowIndex"}),
				
				    AddTechCategory = Table.AddColumn(
				        RemoveIndex,
				        "technology_category",
				        each if [fuel_type_code_pudl] = "solar" then "Solar"
				             else if [fuel_type_code_pudl] = "wind" then "Wind"
				             else if [fuel_type_code_pudl] = "hydro" then "Hydro"
				             else if [fuel_type_code_pudl] = "gas" then "Natural Gas"
				             else if [fuel_type_code_pudl] = "coal" then "Coal"
				             else if [fuel_type_code_pudl] = "nuclear" then "Nuclear"
				             else if [fuel_type_code_pudl] = "oil" then "Petroleum"
				             else "Other",
				        type text
				    ),
				
				    AddRenewable = Table.AddColumn(
				        AddTechCategory,
				        "is_renewable",
				        each List.Contains({"Solar", "Wind", "Hydro"}, [technology_category]),
				        type logical
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(AddRenewable,{{"generator_operating_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

