table DimGenerator
	lineageTag: 6b8f15c4-9646-4fb6-94e5-e7e6a4d6997d

	column plant_id_eia
		dataType: string
		lineageTag: 3319efeb-f85d-4286-861a-124ad10ac5c4
		summarizeBy: none
		sourceColumn: plant_id_eia

		annotation SummarizationSetBy = Automatic

	column generator_id
		dataType: string
		lineageTag: 78a5794c-f73b-4d72-baf1-5a7cc0999eba
		summarizeBy: none
		sourceColumn: generator_id

		annotation SummarizationSetBy = Automatic

	column technology_description
		dataType: string
		lineageTag: fc518354-5ea9-41ee-8045-8226a61a7dcf
		summarizeBy: none
		sourceColumn: technology_description

		annotation SummarizationSetBy = Automatic

	column prime_mover_code
		dataType: string
		lineageTag: e1b43901-300a-4b54-adac-fbf6382d2cdd
		summarizeBy: none
		sourceColumn: prime_mover_code

		annotation SummarizationSetBy = Automatic

	column fuel_type_code_pudl
		dataType: string
		lineageTag: 020217f2-e478-4000-bb18-e8fa68fcab50
		summarizeBy: none
		sourceColumn: fuel_type_code_pudl

		annotation SummarizationSetBy = Automatic

	column technology_category
		dataType: string
		lineageTag: 34f58d40-328c-4318-85b6-7c957ec52242
		summarizeBy: none
		sourceColumn: technology_category

		annotation SummarizationSetBy = Automatic

	column is_renewable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c9a41ce4-ec41-494e-b83b-e5c4bd26681b
		summarizeBy: none
		sourceColumn: is_renewable

		annotation SummarizationSetBy = Automatic

	column GeneratorKey
		dataType: string
		lineageTag: a05258c0-d2d0-450f-abd6-5d1e2d6e6547
		summarizeBy: none
		sourceColumn: GeneratorKey

		annotation SummarizationSetBy = Automatic

	partition DimGenerator = m
		mode: import
		source = ```
				let
				    Source = out_eia__monthly_generators,
				
				    // Select only needed columns
				    SelectColumns = Table.SelectColumns(Source, {
				        "plant_id_eia",
				        "generator_id",
				        "fuel_type_code_pudl",
				        "technology_description",
				        "prime_mover_code"
				    }),
				    
				    // Remove nulls aggressively
				    RemoveNulls = Table.SelectRows(
				        SelectColumns,
				        each [plant_id_eia] <> null 
				        and [generator_id] <> null
				        and [plant_id_eia] <> ""
				        and [generator_id] <> ""
				    ),
				    
				    // Convert and clean
				    CleanData = Table.TransformColumns(
				        RemoveNulls,
				        {
				            {"plant_id_eia", each Text.Trim(Text.From(_)), type text},
				            {"generator_id", each Text.Trim(_), type text}
				        }
				    ),
				    
				    // Add index FIRST (for tie-breaking)
				    AddIndex = Table.AddIndexColumn(CleanData, "RowIndex", 1, 1),
				    
				    // Sort by index to ensure consistent ordering
				    SortByIndex = Table.Sort(AddIndex, {{"RowIndex", Order.Ascending}}),
				    
				    // Create GeneratorKey
				    AddGeneratorKey = Table.AddColumn(
				        SortByIndex,
				        "GeneratorKey",
				        each [plant_id_eia] & "-" & [generator_id],
				        type text
				    ),
				    
				    // CRITICAL: Use Table.Distinct on GeneratorKey (keeps FIRST occurrence)
				    RemoveDuplicateKeys = Table.Distinct(
				        AddGeneratorKey,
				        {"GeneratorKey"}
				    ),
				    
				    // Remove the temporary RowIndex column
				    RemoveIndex = Table.RemoveColumns(RemoveDuplicateKeys, {"RowIndex"}),
				    
				    // Add technology category
				    AddTechCategory = Table.AddColumn(
				        RemoveIndex,
				        "technology_category",
				        each if [fuel_type_code_pudl] = "solar" then "Solar"
				             else if [fuel_type_code_pudl] = "wind" then "Wind"
				             else if [fuel_type_code_pudl] = "hydro" then "Hydro"
				             else if [fuel_type_code_pudl] = "gas" then "Natural Gas"
				             else if [fuel_type_code_pudl] = "coal" then "Coal"
				             else if [fuel_type_code_pudl] = "nuclear" then "Nuclear"
				             else if [fuel_type_code_pudl] = "oil" then "Petroleum"
				             else "Other",
				        type text
				    ),
				    
				    AddRenewable = Table.AddColumn(
				        AddTechCategory,
				        "is_renewable",
				        each List.Contains({"Solar", "Wind", "Hydro"}, [technology_category]),
				        type logical
				    )
				in
				    AddRenewable
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

