table DimGenerator
	lineageTag: 6b8f15c4-9646-4fb6-94e5-e7e6a4d6997d

	column plant_id_eia
		dataType: int64
		formatString: 0
		lineageTag: 3319efeb-f85d-4286-861a-124ad10ac5c4
		summarizeBy: none
		sourceColumn: plant_id_eia

		annotation SummarizationSetBy = Automatic

	column generator_id
		dataType: string
		lineageTag: 78a5794c-f73b-4d72-baf1-5a7cc0999eba
		summarizeBy: none
		sourceColumn: generator_id

		annotation SummarizationSetBy = Automatic

	column unit_id_pudl
		dataType: int64
		formatString: 0
		lineageTag: 8ff6b5e7-ca1a-4925-9489-8fbed89e78a0
		summarizeBy: sum
		sourceColumn: unit_id_pudl

		annotation SummarizationSetBy = Automatic

	column technology_description
		dataType: string
		lineageTag: fc518354-5ea9-41ee-8045-8226a61a7dcf
		summarizeBy: none
		sourceColumn: technology_description

		annotation SummarizationSetBy = Automatic

	column energy_source_code_1
		dataType: string
		lineageTag: cef00888-4665-47c8-9895-f4eb49de4e02
		summarizeBy: none
		sourceColumn: energy_source_code_1

		annotation SummarizationSetBy = Automatic

	column energy_source_code_2
		dataType: string
		lineageTag: 15cc17cd-ab18-4144-80dc-08eacd30d80b
		summarizeBy: none
		sourceColumn: energy_source_code_2

		annotation SummarizationSetBy = Automatic

	column energy_source_code_3
		dataType: string
		lineageTag: 74d21278-3f45-42c7-b1b7-2176d78405e1
		summarizeBy: none
		sourceColumn: energy_source_code_3

		annotation SummarizationSetBy = Automatic

	column prime_mover_code
		dataType: string
		lineageTag: e1b43901-300a-4b54-adac-fbf6382d2cdd
		summarizeBy: none
		sourceColumn: prime_mover_code

		annotation SummarizationSetBy = Automatic

	column fuel_type_code_pudl
		dataType: string
		lineageTag: 020217f2-e478-4000-bb18-e8fa68fcab50
		summarizeBy: none
		sourceColumn: fuel_type_code_pudl

		annotation SummarizationSetBy = Automatic

	column operational_status
		dataType: string
		lineageTag: b16db692-0f66-4166-9ca7-0844d7884855
		summarizeBy: none
		sourceColumn: operational_status

		annotation SummarizationSetBy = Automatic

	column operational_status_code
		dataType: string
		lineageTag: d3117a99-5db2-484b-ac70-60663b5d8af9
		summarizeBy: none
		sourceColumn: operational_status_code

		annotation SummarizationSetBy = Automatic

	column generator_operating_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 60b5c171-ad33-4ee7-a968-ac3dda16afa4
		summarizeBy: none
		sourceColumn: generator_operating_date

		variation Variation
			isDefault
			relationship: 6293bbcd-2cb0-44bb-89c4-09facb089a80
			defaultHierarchy: LocalDateTable_be514196-bc0e-44dd-a044-1ea3af0f72f2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column generator_retirement_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ab48fc22-ad80-45f8-a807-5c7782c49970
		summarizeBy: none
		sourceColumn: generator_retirement_date

		variation Variation
			isDefault
			relationship: 009b8a0d-a04a-4b31-8e01-63fe5d2aa567
			defaultHierarchy: LocalDateTable_5498398a-8a22-4019-abea-7615c185af16.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column planned_generator_retirement_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 433b7a0e-da4b-4d82-a729-708293e4974f
		summarizeBy: none
		sourceColumn: planned_generator_retirement_date

		variation Variation
			isDefault
			relationship: 03268f42-8b0b-4e07-8fb5-43e7e21d8464
			defaultHierarchy: LocalDateTable_51fc3c93-d1e6-41e2-86ed-da6bc0a84130.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ownership_code
		dataType: string
		lineageTag: 3e8265a9-3069-41c8-a924-99c748687ce8
		summarizeBy: none
		sourceColumn: ownership_code

		annotation SummarizationSetBy = Automatic

	column can_cofire_fuels
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7c2d9cef-4c9d-4f27-b662-398280dbec69
		summarizeBy: none
		sourceColumn: can_cofire_fuels

		annotation SummarizationSetBy = Automatic

	column can_burn_multiple_fuels
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 01c60fc7-4642-42f9-b33b-6c959e25ccca
		summarizeBy: none
		sourceColumn: can_burn_multiple_fuels

		annotation SummarizationSetBy = Automatic

	column can_switch_when_operating
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 66542d79-3862-4466-90fa-a8fc874a770c
		summarizeBy: none
		sourceColumn: can_switch_when_operating

		annotation SummarizationSetBy = Automatic

	column associated_combined_heat_power
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 784300f1-9af3-4a33-a40c-bd50010dbcb0
		summarizeBy: none
		sourceColumn: associated_combined_heat_power

		annotation SummarizationSetBy = Automatic

	column carbon_capture
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 921a1498-027c-4358-be3a-c6bef8ef9927
		summarizeBy: none
		sourceColumn: carbon_capture

		annotation SummarizationSetBy = Automatic

	column distributed_generation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b61cc1ca-10fa-468a-92c5-e8f74915dd5a
		summarizeBy: none
		sourceColumn: distributed_generation

		annotation SummarizationSetBy = Automatic

	column energy_storage_capacity_mwh
		dataType: double
		lineageTag: 174fd1f2-addc-4eca-8242-df12c36cee90
		summarizeBy: sum
		sourceColumn: energy_storage_capacity_mwh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column technology_category
		dataType: string
		lineageTag: 34f58d40-328c-4318-85b6-7c957ec52242
		summarizeBy: none
		sourceColumn: technology_category

		annotation SummarizationSetBy = Automatic

	column is_renewable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c9a41ce4-ec41-494e-b83b-e5c4bd26681b
		summarizeBy: none
		sourceColumn: is_renewable

		annotation SummarizationSetBy = Automatic

	partition DimGenerator = m
		mode: import
		source = ```
				let
				    Source = out_eia__monthly_generators,
				
				    // Select generator attributes
				    SelectGeneratorColumns = Table.SelectColumns(Source, {
				        "plant_id_eia",
				        "generator_id",
				        "unit_id_pudl",
				        "technology_description",
				        "energy_source_code_1",
				        "energy_source_code_2",
				        "energy_source_code_3",
				        "prime_mover_code",
				        "fuel_type_code_pudl",
				        "operational_status",
				        "operational_status_code",
				        "generator_operating_date",
				        "generator_retirement_date",
				        "planned_generator_retirement_date",
				        "ownership_code",
				        "can_cofire_fuels",
				        "can_burn_multiple_fuels",
				        "can_switch_when_operating",
				        "associated_combined_heat_power",
				        "carbon_capture",
				        "distributed_generation",
				        "energy_storage_capacity_mwh"
				    }),
				    
				    // Remove duplicates (keeps first occurrence which is most recent after sorting)
				    SortByDate = Table.Sort(SelectGeneratorColumns, {{"generator_operating_date", Order.Descending}}),
				    RemoveDuplicates = Table.Distinct(SortByDate, {"plant_id_eia", "generator_id"}),
				    
				    // Add technology categorization
				    AddTechnologyCategory = Table.AddColumn(RemoveDuplicates, "technology_category", each
				        if [fuel_type_code_pudl] = "solar" then "Solar"
				        else if [fuel_type_code_pudl] = "wind" then "Wind"
				        else if [fuel_type_code_pudl] = "hydro" then "Hydro"
				        else if [fuel_type_code_pudl] = "gas" then "Natural Gas"
				        else if [fuel_type_code_pudl] = "coal" then "Coal"
				        else if [fuel_type_code_pudl] = "nuclear" then "Nuclear"
				        else if [fuel_type_code_pudl] = "oil" then "Petroleum"
				        else if [fuel_type_code_pudl] = "other" then "Other/Storage"
				        else "Unknown",
				    type text),
				    
				    // Add renewable flag
				    AddRenewableFlag = Table.AddColumn(AddTechnologyCategory, "is_renewable", each
				        List.Contains({"Solar", "Wind", "Hydro"}, [technology_category]),
				    type logical)
				in
				    AddRenewableFlag
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

