table DimGenerator
	lineageTag: cf575844-b711-4863-beac-00684490e3d4

	column plant_id_eia
		dataType: string
		lineageTag: eb319ea3-e523-4f0e-814d-b1e07cc04e88
		summarizeBy: none
		sourceColumn: plant_id_eia

		annotation SummarizationSetBy = Automatic

	column generator_id
		dataType: string
		lineageTag: af992e6c-09e9-4e53-8cf3-5252e8b698e3
		summarizeBy: none
		sourceColumn: generator_id

		annotation SummarizationSetBy = Automatic

	column fuel_type_code_pudl
		dataType: string
		lineageTag: d46d9783-5f51-496b-894e-d57112f55294
		summarizeBy: none
		sourceColumn: fuel_type_code_pudl

		annotation SummarizationSetBy = Automatic

	column technology_description
		dataType: string
		lineageTag: 754b9c64-ae38-40dd-ad45-c7fdb388749d
		summarizeBy: none
		sourceColumn: technology_description

		annotation SummarizationSetBy = Automatic

	column prime_mover_code
		dataType: string
		lineageTag: 5ba81e88-9637-470f-a633-233c4f55d6f9
		summarizeBy: none
		sourceColumn: prime_mover_code

		annotation SummarizationSetBy = Automatic

	column GeneratorKey
		dataType: string
		lineageTag: 5f1eee99-b2a2-4f9a-bfff-79d955a05892
		summarizeBy: none
		sourceColumn: GeneratorKey

		annotation SummarizationSetBy = Automatic

	column technology_category
		dataType: string
		lineageTag: c22b8c6e-17ce-4f49-84aa-3c99562a5caa
		summarizeBy: none
		sourceColumn: technology_category

		annotation SummarizationSetBy = Automatic

	column is_renewable
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 644bf5d3-fd03-4305-bc9a-afe28f61243e
		summarizeBy: none
		sourceColumn: is_renewable

		annotation SummarizationSetBy = Automatic

	hierarchy 'Technology Hierarchy'
		lineageTag: fe625c21-b1d3-4302-8e14-5ef95c873b49

		level technology_category
			lineageTag: 0a6a87b0-8047-4a40-a1b7-fcb73f26693e
			column: technology_category

		level fuel_type_code_pudl
			lineageTag: 3b5eb924-8a71-4f7f-815a-c8274bf7faf5
			column: fuel_type_code_pudl

		level technology_description
			lineageTag: e206ae4e-7b63-4cfb-af53-7a9ed233cd01
			column: technology_description

	partition DimGenerator = m
		mode: import
		source = ```
				let
				    Source = out_eia__monthly_generators,
				
				// Select only needed columns
				    SelectColumns = Table.SelectColumns(Source, {
				        "plant_id_eia",
				        "generator_id",
				        "fuel_type_code_pudl",
				        "technology_description",
				        "prime_mover_code"
				    }),
				    
				    // Remove nulls aggressively
				    RemoveNulls = Table.SelectRows(
				        SelectColumns,
				        each [plant_id_eia] <> null 
				        and [generator_id] <> null
				        and [plant_id_eia] <> ""
				        and [generator_id] <> ""
				    ),
				    
				    // Convert and clean
				    CleanData = Table.TransformColumns(
				        RemoveNulls,
				        {
				            {"plant_id_eia", each Text.Trim(Text.From(_)), type text},
				            {"generator_id", each Text.Trim(_), type text}
				        }
				    ),
				    
				    // Add index FIRST (for tie-breaking)
				    AddIndex = Table.AddIndexColumn(CleanData, "RowIndex", 1, 1),
				    
				    // Sort by index to ensure consistent ordering
				    SortByIndex = Table.Sort(AddIndex, {{"RowIndex", Order.Ascending}}),
				    
				    // Create GeneratorKey
				    AddGeneratorKey = Table.AddColumn(
				        SortByIndex,
				        "GeneratorKey",
				        each [plant_id_eia] & "-" & [generator_id],
				        type text
				    ),
				    
				    // CRITICAL: Use Table.Distinct on GeneratorKey (keeps FIRST occurrence)
				    RemoveDuplicateKeys = Table.Distinct(
				        AddGeneratorKey,
				        {"GeneratorKey"}
				    ),
				    
				    // Remove the temporary RowIndex column
				    RemoveIndex = Table.RemoveColumns(RemoveDuplicateKeys, {"RowIndex"}),
				    
				    // Add technology category
				    AddTechCategory = Table.AddColumn(
				        RemoveIndex,
				        "technology_category",
				        each if [fuel_type_code_pudl] = "solar" then "Solar"
				             else if [fuel_type_code_pudl] = "wind" then "Wind"
				             else if [fuel_type_code_pudl] = "hydro" then "Hydro"
				             else if [fuel_type_code_pudl] = "gas" then "Natural Gas"
				             else if [fuel_type_code_pudl] = "coal" then "Coal"
				             else if [fuel_type_code_pudl] = "nuclear" then "Nuclear"
				             else if [fuel_type_code_pudl] = "oil" then "Petroleum"
				             else "Other",
				        type text
				    ),
				    
				    AddRenewable = Table.AddColumn(
				        AddTechCategory,
				        "is_renewable",
				        each List.Contains({"Solar", "Wind", "Hydro"}, [technology_category]),
				        type logical
				    ),
				    #"Uppercased Text" = Table.TransformColumns(AddRenewable,{{"GeneratorKey", Text.Upper, type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Uppercased Text", {"GeneratorKey"})
				in
				    #"Removed Duplicates"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

