table DimPlant
	lineageTag: 96baf361-33c3-427e-9218-27b6a41357b0

	column plant_id_eia
		dataType: int64
		formatString: 0
		lineageTag: 48ac2440-9c53-48cf-b284-900030618639
		summarizeBy: none
		sourceColumn: plant_id_eia

		annotation SummarizationSetBy = Automatic

	column plant_id_pudl
		dataType: int64
		formatString: 0
		lineageTag: b058e7ea-bb06-431f-bedb-81de2a6534cf
		summarizeBy: none
		sourceColumn: plant_id_pudl

		annotation SummarizationSetBy = Automatic

	column plant_name_eia
		dataType: string
		lineageTag: d836449e-6499-4c7c-9a9c-8e32b4d17afa
		summarizeBy: none
		sourceColumn: plant_name_eia

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 11247b38-4fcc-4655-b221-fd6f63db2f48
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 89f58406-621d-491c-a23f-5d7c2d8a62bc
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column city
		dataType: string
		lineageTag: 453a3144-0ef9-4f35-bf03-369dff9bbbaa
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column county
		dataType: string
		lineageTag: 6975e4d0-5ba5-4838-9cac-9c2ed5979178
		dataCategory: County
		summarizeBy: none
		sourceColumn: county

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 0014649b-07d1-4737-babb-8a247409bcea
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column zip_code
		dataType: string
		lineageTag: 59bcac9a-d166-44e8-8182-912447cee980
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: zip_code

		annotation SummarizationSetBy = Automatic

	column street_address
		dataType: string
		lineageTag: cd298fa3-134d-46f4-b96e-14f921a5836e
		dataCategory: Address
		summarizeBy: none
		sourceColumn: street_address

		annotation SummarizationSetBy = Automatic

	column timezone
		dataType: string
		lineageTag: 4e14f5a1-7ac1-4ffe-af59-7417c6255b20
		summarizeBy: none
		sourceColumn: timezone

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 715ea816-a539-47ec-aa76-86cef8ac3028
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	/// State-County Combination (for geography drill)
	column State-County = DimPlant[state] & "-" & DimPlant[county]
		lineageTag: f17bb5e5-a59a-49e9-b34a-3287d712a23c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Coastal Plant' =
			IF(
			                    DimPlant[state] IN { "CA", "OR", "WA", "AK", "HI",
			        "TX", "LA", "MS", "AL", "FL", "GA", "SC", "NC", "VA", "MD", "DE", "NJ", "NY", "CT", "RI", "MA", "NH", "ME"
			                    },
			                    TRUE(),
			                    FALSE()
			                )
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c360bada-ec49-424b-8d57-7fca5a73a859
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Geographic Hierarchy'
		lineageTag: 3f0176eb-1679-4d57-98fc-d43e38ef8d69

		level region
			lineageTag: 27c83570-77bd-4203-95fe-60c8c6c6e5a6
			column: region

		level state
			lineageTag: b2dbe1de-50b5-4d38-be1c-0f223d2c0dca
			column: state

		level county
			lineageTag: fecc4b79-62eb-4c0b-ba72-5fdee869941c
			column: county

		level city
			lineageTag: b5a50adc-6aed-4083-b1cd-15c76f8294cf
			column: city

		level plant_name_eia
			lineageTag: c5cbbf94-30bf-4e40-b0d2-fba13324a7b9
			column: plant_name_eia

	partition DimPlant = m
		mode: import
		source = ```
				let
				    Source = out_eia__monthly_generators,
				
				    // Select only plant-related columns
				    SelectPlantColumns = Table.SelectColumns(Source, {
				        "plant_id_eia",
				        "plant_id_pudl",
				        "plant_name_eia",
				        "latitude",
				        "longitude",
				        "city",
				        "county",
				        "state",
				        "zip_code",
				        "street_address",
				        "timezone"
				    }),
				    
				    // Remove duplicate plants (get most recent/complete record)
				    RemoveDuplicates = Table.Distinct(SelectPlantColumns, {"plant_id_eia"}),
				    
				    // Add calculated geographic columns
				    AddRegion = Table.AddColumn(RemoveDuplicates, "region", each
				        if List.Contains({"ME", "NH", "VT", "MA", "RI", "CT"}, [state]) then "New England"
				        else if List.Contains({"NY", "NJ", "PA"}, [state]) then "Mid-Atlantic"
				        else if List.Contains({"OH", "IN", "IL", "MI", "WI"}, [state]) then "Midwest"
				        else if List.Contains({"MN", "IA", "MO", "ND", "SD", "NE", "KS"}, [state]) then "Great Plains"
				        else if List.Contains({"DE", "MD", "DC", "VA", "WV", "NC", "SC", "GA", "FL"}, [state]) then "Southeast"
				        else if List.Contains({"KY", "TN", "AL", "MS", "AR", "LA", "OK", "TX"}, [state]) then "South"
				        else if List.Contains({"MT", "ID", "WY", "NV", "UT", "CO", "AZ", "NM"}, [state]) then "Mountain"
				        else if List.Contains({"WA", "OR", "CA", "AK", "HI"}, [state]) then "Pacific"
				        else "Other",
				    type text)
				in
				    AddRegion
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

