table DimPlant
	lineageTag: 96baf361-33c3-427e-9218-27b6a41357b0

	column plant_id_eia
		dataType: int64
		formatString: 0
		lineageTag: 48ac2440-9c53-48cf-b284-900030618639
		summarizeBy: none
		sourceColumn: plant_id_eia

		annotation SummarizationSetBy = Automatic

	column plant_id_pudl
		dataType: int64
		formatString: 0
		lineageTag: b058e7ea-bb06-431f-bedb-81de2a6534cf
		summarizeBy: none
		sourceColumn: plant_id_pudl

		annotation SummarizationSetBy = Automatic

	column plant_name_eia
		dataType: string
		lineageTag: d836449e-6499-4c7c-9a9c-8e32b4d17afa
		summarizeBy: none
		sourceColumn: plant_name_eia

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 11247b38-4fcc-4655-b221-fd6f63db2f48
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 89f58406-621d-491c-a23f-5d7c2d8a62bc
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column city
		dataType: string
		lineageTag: 453a3144-0ef9-4f35-bf03-369dff9bbbaa
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column county
		dataType: string
		lineageTag: 6975e4d0-5ba5-4838-9cac-9c2ed5979178
		summarizeBy: none
		sourceColumn: county

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 0014649b-07d1-4737-babb-8a247409bcea
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column zip_code
		dataType: string
		lineageTag: 59bcac9a-d166-44e8-8182-912447cee980
		summarizeBy: none
		sourceColumn: zip_code

		annotation SummarizationSetBy = Automatic

	column street_address
		dataType: string
		lineageTag: cd298fa3-134d-46f4-b96e-14f921a5836e
		summarizeBy: none
		sourceColumn: street_address

		annotation SummarizationSetBy = Automatic

	column timezone
		dataType: string
		lineageTag: 4e14f5a1-7ac1-4ffe-af59-7417c6255b20
		summarizeBy: none
		sourceColumn: timezone

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 715ea816-a539-47ec-aa76-86cef8ac3028
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	partition DimPlant = m
		mode: import
		source = ```
				let
				    Source = out_eia__monthly_generators,
				
				    // Select only plant-related columns
				    SelectPlantColumns = Table.SelectColumns(Source, {
				        "plant_id_eia",
				        "plant_id_pudl",
				        "plant_name_eia",
				        "latitude",
				        "longitude",
				        "city",
				        "county",
				        "state",
				        "zip_code",
				        "street_address",
				        "timezone"
				    }),
				    
				    // Remove duplicate plants (get most recent/complete record)
				    RemoveDuplicates = Table.Distinct(SelectPlantColumns, {"plant_id_eia"}),
				    
				    // Add calculated geographic columns
				    AddRegion = Table.AddColumn(RemoveDuplicates, "region", each
				        if List.Contains({"ME", "NH", "VT", "MA", "RI", "CT"}, [state]) then "New England"
				        else if List.Contains({"NY", "NJ", "PA"}, [state]) then "Mid-Atlantic"
				        else if List.Contains({"OH", "IN", "IL", "MI", "WI"}, [state]) then "Midwest"
				        else if List.Contains({"MN", "IA", "MO", "ND", "SD", "NE", "KS"}, [state]) then "Great Plains"
				        else if List.Contains({"DE", "MD", "DC", "VA", "WV", "NC", "SC", "GA", "FL"}, [state]) then "Southeast"
				        else if List.Contains({"KY", "TN", "AL", "MS", "AR", "LA", "OK", "TX"}, [state]) then "South"
				        else if List.Contains({"MT", "ID", "WY", "NV", "UT", "CO", "AZ", "NM"}, [state]) then "Mountain"
				        else if List.Contains({"WA", "OR", "CA", "AK", "HI"}, [state]) then "Pacific"
				        else "Other",
				    type text)
				in
				    AddRegion
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

