table DimUtility
	lineageTag: 2131c3b3-538e-4b9a-8706-6f7d65e9054d

	column utility_id_eia
		dataType: string
		lineageTag: e0e6fee9-6bb0-4832-bf5c-f006a46f04db
		summarizeBy: none
		sourceColumn: utility_id_eia

		annotation SummarizationSetBy = Automatic

	column utility_id_pudl
		dataType: double
		formatString: 0
		lineageTag: 91ca2f1f-c5e0-48b4-b296-ed7720d6f086
		summarizeBy: none
		sourceColumn: utility_id_pudl

		annotation SummarizationSetBy = Automatic

	column utility_name_eia
		dataType: string
		lineageTag: 5c3a5bc5-9890-4b31-8d5d-611935f4c689
		summarizeBy: none
		sourceColumn: utility_name_eia

		annotation SummarizationSetBy = Automatic

	partition DimUtility = m
		mode: import
		source =
				let
				    Source = out_eia__monthly_generators,
				
				SelectUtilityColumns = Table.SelectColumns(Source, {
				        "utility_id_eia",
				        "utility_id_pudl",
				        "utility_name_eia"
				    }),
				
				    // Normalize types/text first
				    Clean = Table.TransformColumns(
				        SelectUtilityColumns,
				        {
				            {"utility_id_eia", each Text.Trim(Text.Clean(Text.From(_))), type text},
				            {"utility_id_pudl", each try Number.From(_) otherwise null, type number},
				            {"utility_name_eia", each Text.Trim(Text.Clean(Text.From(_))), type text}
				        }
				    ),
				
				    // Remove null/blank keys (critical for 1-side relationship)
				    RemoveBlankKeys = Table.SelectRows(
				        Clean,
				        each [utility_id_eia] <> null and [utility_id_eia] <> ""
				    ),
				
				    // Now dedupe by the key
				    RemoveDuplicates = Table.Distinct(RemoveBlankKeys, {"utility_id_eia"})
				in
				    RemoveDuplicates

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

