table FactGeneratorMonthly
	lineageTag: 657d9829-609d-49f4-8582-e41e162ed9be

	column plant_id_eia
		dataType: int64
		formatString: 0
		lineageTag: fe3c97c0-2721-4d29-ba44-a522785603b8
		summarizeBy: none
		sourceColumn: plant_id_eia

		annotation SummarizationSetBy = Automatic

	column generator_id
		dataType: string
		lineageTag: 4d064114-2ca9-417a-8525-0de2bcd02c68
		summarizeBy: none
		sourceColumn: generator_id

		annotation SummarizationSetBy = Automatic

	column report_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 097a054f-3e7c-4dae-8edb-f208d2b7f972
		summarizeBy: none
		sourceColumn: report_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column utility_id_eia
		dataType: int64
		formatString: 0
		lineageTag: b514abec-c807-4271-9106-e920e0d048c4
		summarizeBy: none
		sourceColumn: utility_id_eia

		annotation SummarizationSetBy = Automatic

	column balancing_authority_code_eia
		dataType: string
		lineageTag: 533387ba-3a56-40ea-a023-c490adab7bbe
		summarizeBy: none
		sourceColumn: balancing_authority_code_eia

		annotation SummarizationSetBy = Automatic

	column capacity_mw
		dataType: double
		lineageTag: 53d84204-9acb-401f-9373-e4689c60b54a
		summarizeBy: sum
		sourceColumn: capacity_mw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column capacity_factor
		dataType: double
		lineageTag: 920df652-3692-430b-95ae-6aff46bb7e71
		summarizeBy: sum
		sourceColumn: capacity_factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fuel_cost_per_mmbtu
		dataType: double
		lineageTag: 578e8061-d1b7-454d-b952-d27a66b0ce6a
		summarizeBy: sum
		sourceColumn: fuel_cost_per_mmbtu

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fuel_cost_per_mwh
		dataType: double
		lineageTag: 5cc7aba7-8f12-42b5-9778-8bf8a2e1f668
		summarizeBy: sum
		sourceColumn: fuel_cost_per_mwh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit_heat_rate_mmbtu_per_mwh
		dataType: double
		lineageTag: bc232038-b4fb-4e53-a7bc-5ad272c46783
		summarizeBy: sum
		sourceColumn: unit_heat_rate_mmbtu_per_mwh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column net_generation_mwh
		dataType: double
		lineageTag: 3d29f152-c4f2-44dd-bbc1-cde3389c36a2
		summarizeBy: sum
		sourceColumn: net_generation_mwh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_fuel_cost
		dataType: double
		lineageTag: a78e5e19-63a6-4fa9-8c3b-a27a95e43d75
		summarizeBy: sum
		sourceColumn: total_fuel_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_mmbtu
		dataType: double
		lineageTag: 4173eefc-0976-47cd-b5bc-ce707e0eada5
		summarizeBy: sum
		sourceColumn: total_mmbtu

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column minimum_load_mw
		dataType: double
		lineageTag: 9380cbd3-cc13-4296-8fda-c237b6ab6da1
		summarizeBy: sum
		sourceColumn: minimum_load_mw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column summer_capacity_mw
		dataType: double
		lineageTag: 9dcfd42f-b1a0-46cf-8c68-009a5bdbb6e6
		summarizeBy: sum
		sourceColumn: summer_capacity_mw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column winter_capacity_mw
		dataType: double
		lineageTag: eecd3ab5-b800-42f0-93f7-1731a7473237
		summarizeBy: sum
		sourceColumn: winter_capacity_mw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column summer_estimated_capability_mw
		dataType: double
		lineageTag: 697fc86d-dc06-499d-803a-f07155b7ad1f
		summarizeBy: sum
		sourceColumn: summer_estimated_capability_mw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column winter_estimated_capability_mw
		dataType: double
		lineageTag: 947781be-a5f7-4499-8ea7-ca77b90a15e3
		summarizeBy: sum
		sourceColumn: winter_estimated_capability_mw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column operational_status_code
		dataType: string
		lineageTag: d2fa5438-79a6-4d99-a6c6-eb9142c1b9bb
		summarizeBy: none
		sourceColumn: operational_status_code

		annotation SummarizationSetBy = Automatic

	column capacity_utilization_pct
		dataType: double
		lineageTag: 977562e7-a85c-4172-ae45-bf23274d9bf1
		summarizeBy: sum
		sourceColumn: capacity_utilization_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_co2_tons
		dataType: double
		lineageTag: 00275d94-3219-4ad4-bad9-857a8ffc2a59
		summarizeBy: sum
		sourceColumn: estimated_co2_tons

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data_quality_flag
		dataType: string
		lineageTag: a6c35fe2-7c08-40fb-854b-6d6b9328c310
		summarizeBy: none
		sourceColumn: data_quality_flag

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 8056ea3e-cec7-45d0-8f42-51ac56c023a2
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: f0070123-6874-4dc9-b2f6-b164742a198e
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column GeneratorKey = FactGeneratorMonthly[plant_id_eia] & "-" & FactGeneratorMonthly[generator_id]
		lineageTag: 9abf8ffc-e3b8-442d-9b69-bf112f4cc5df
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FactGeneratorMonthly = m
		mode: import
		source = ```
				let
				    Source = out_eia__monthly_generators,
				
				    // Select only keys and measure columns for fact table
				    SelectFactColumns = Table.SelectColumns(Source, {
				        // Keys
				        "plant_id_eia",
				        "generator_id",
				        "report_date",
				        "utility_id_eia",
				        "balancing_authority_code_eia",
				        
				        // Measure columns (numeric values that change monthly)
				        "capacity_mw",
				        "capacity_factor",
				        "fuel_cost_per_mmbtu",
				        "fuel_cost_per_mwh",
				        "unit_heat_rate_mmbtu_per_mwh",
				        "net_generation_mwh",
				        "total_fuel_cost",
				        "total_mmbtu",
				        "minimum_load_mw",
				        "summer_capacity_mw",
				        "winter_capacity_mw",
				        "summer_estimated_capability_mw",
				        "winter_estimated_capability_mw",
				        
				        // Keep operational status as it can change monthly
				        "operational_status_code"
				    }),
				    
				    // Add calculated measures
				    AddCapacityUtilization = Table.AddColumn(
				        SelectFactColumns,
				        "capacity_utilization_pct",
				        each if [capacity_mw] = null or [capacity_mw] = 0 or [net_generation_mwh] = null
				             then null
				             else ([net_generation_mwh] / ([capacity_mw] * 730)) * 100,  // 730 hours avg per month
				        type number
				    ),
				    
				    // Calculate emissions estimate (simplified - actual formula is more complex)
				    AddCO2Estimate = Table.AddColumn(
				        AddCapacityUtilization,
				        "estimated_co2_tons",
				        each if [total_mmbtu] = null then null
				             else [total_mmbtu] * 0.053,  // Simplified emission factor
				        type number
				    ),
				    
				    // Add data quality flag HERE (after all other columns are ready)
				    AddDataQualityFlag = Table.AddColumn(
				        AddCO2Estimate,
				        "data_quality_flag",
				        each if [net_generation_mwh] = null and [capacity_factor] = null 
				             then "Incomplete" 
				             else "Complete",
				        type text
				    ),
				    
				    // Add year and month for easier filtering
				    AddYear = Table.AddColumn(AddDataQualityFlag, "year", each Date.Year([report_date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddYear, "month", each Date.Month([report_date]), Int64.Type),
				    
				    // Final type check
				    FinalFact = AddMonth
				in
				    FinalFact
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

